/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from "./routes/__root"
import { Route as DashboardRouteRouteImport } from "./routes/dashboard/route"
import { Route as IndexRouteImport } from "./routes/index"
import { Route as DashboardIndexRouteImport } from "./routes/dashboard/index"
import { Route as DashboardViolationsRouteImport } from "./routes/dashboard/violations"
import { Route as DashboardOfficersRouteImport } from "./routes/dashboard/officers"
import { Route as DashboardAnalyticsRouteImport } from "./routes/dashboard/analytics"

const DashboardRouteRoute = DashboardRouteRouteImport.update({
  id: "/dashboard",
  path: "/dashboard",
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardViolationsRoute = DashboardViolationsRouteImport.update({
  id: "/violations",
  path: "/violations",
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardOfficersRoute = DashboardOfficersRouteImport.update({
  id: "/officers",
  path: "/officers",
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardAnalyticsRoute = DashboardAnalyticsRouteImport.update({
  id: "/analytics",
  path: "/analytics",
  getParentRoute: () => DashboardRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  "/": typeof IndexRoute
  "/dashboard": typeof DashboardRouteRouteWithChildren
  "/dashboard/analytics": typeof DashboardAnalyticsRoute
  "/dashboard/officers": typeof DashboardOfficersRoute
  "/dashboard/violations": typeof DashboardViolationsRoute
  "/dashboard/": typeof DashboardIndexRoute
}
export interface FileRoutesByTo {
  "/": typeof IndexRoute
  "/dashboard/analytics": typeof DashboardAnalyticsRoute
  "/dashboard/officers": typeof DashboardOfficersRoute
  "/dashboard/violations": typeof DashboardViolationsRoute
  "/dashboard": typeof DashboardIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  "/": typeof IndexRoute
  "/dashboard": typeof DashboardRouteRouteWithChildren
  "/dashboard/analytics": typeof DashboardAnalyticsRoute
  "/dashboard/officers": typeof DashboardOfficersRoute
  "/dashboard/violations": typeof DashboardViolationsRoute
  "/dashboard/": typeof DashboardIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | "/"
    | "/dashboard"
    | "/dashboard/analytics"
    | "/dashboard/officers"
    | "/dashboard/violations"
    | "/dashboard/"
  fileRoutesByTo: FileRoutesByTo
  to:
    | "/"
    | "/dashboard/analytics"
    | "/dashboard/officers"
    | "/dashboard/violations"
    | "/dashboard"
  id:
    | "__root__"
    | "/"
    | "/dashboard"
    | "/dashboard/analytics"
    | "/dashboard/officers"
    | "/dashboard/violations"
    | "/dashboard/"
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRouteRoute: typeof DashboardRouteRouteWithChildren
}

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/dashboard": {
      id: "/dashboard"
      path: "/dashboard"
      fullPath: "/dashboard"
      preLoaderRoute: typeof DashboardRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/": {
      id: "/"
      path: "/"
      fullPath: "/"
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/dashboard/": {
      id: "/dashboard/"
      path: "/"
      fullPath: "/dashboard/"
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    "/dashboard/violations": {
      id: "/dashboard/violations"
      path: "/violations"
      fullPath: "/dashboard/violations"
      preLoaderRoute: typeof DashboardViolationsRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    "/dashboard/officers": {
      id: "/dashboard/officers"
      path: "/officers"
      fullPath: "/dashboard/officers"
      preLoaderRoute: typeof DashboardOfficersRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    "/dashboard/analytics": {
      id: "/dashboard/analytics"
      path: "/analytics"
      fullPath: "/dashboard/analytics"
      preLoaderRoute: typeof DashboardAnalyticsRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
  }
}

interface DashboardRouteRouteChildren {
  DashboardAnalyticsRoute: typeof DashboardAnalyticsRoute
  DashboardOfficersRoute: typeof DashboardOfficersRoute
  DashboardViolationsRoute: typeof DashboardViolationsRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
}

const DashboardRouteRouteChildren: DashboardRouteRouteChildren = {
  DashboardAnalyticsRoute: DashboardAnalyticsRoute,
  DashboardOfficersRoute: DashboardOfficersRoute,
  DashboardViolationsRoute: DashboardViolationsRoute,
  DashboardIndexRoute: DashboardIndexRoute,
}

const DashboardRouteRouteWithChildren = DashboardRouteRoute._addFileChildren(
  DashboardRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRouteRoute: DashboardRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
